// <auto-generated />
using System;
using CsvProcessorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsvProcessorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627073241_AddUploadedMachineIdsToProcessingResult")]
    partial class AddUploadedMachineIdsToProcessingResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CsvProcessorApp.Models.ProcessingResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FullyRefundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartiallyRefundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartiallyRefundedTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefundedTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRefundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalUsedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedMachineIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessingResults");
                });

            modelBuilder.Entity("CsvProcessorApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
