// <auto-generated />
using System;
using CsvProcessorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsvProcessorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250616061307_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CsvProcessorApp.Models.ProcessingResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FullyRefundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartiallyRefundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartiallyRefundedTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefundedTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRefundedAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalUsedAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
